const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CURRENT_SONG_ID: "SET_CURRENT_SONG_ID",
  SET_CURRENT_SONG_DATA: "SET_CURRENT_SONG_DATA",
  SET_CURRENT_ALBUM_ID: "SET_CURRENT_ALBUM_ID",
  SET_RECENT_SONG: "SET_RECENT_SONG",
  PLAY: "PLAY",
  SET_ALBUM: "SET_ALBUM",
  PLAYLIST: "PLAYLIST",
  LOADING: "LOADING",
};

export default actionTypes;
